@echo on

rem 设置环境变量

set HW_VER=Burn_FPM183B_10
set SW_VER=105
rem 协议版本 00--ML
set PROTOCOL_VER_ML_TZ=00
set PROTOCOL_VER_SY=12
set PACK_DATE=%date:~0,4%%date:~5,2%%date:~8,2%

set APPPATH=%cd%\..\..\OBJ
set LOADERPATH=%cd%
set XMLPATH=%cd%\..\
set OUTPUTPATH=%cd%

set APPBIN=%APPPATH%\ML_FPM.bin
set LOADERBIN=%LOADERPATH%\ML_n32g4fr_loader.bin
set XMLFILE_ML_TZ=%XMLPATH%\SystemSetting_ML_TZ.xml
set XMLFILE_SY=%XMLPATH%\SystemSetting_SY.xml
set OUTPUTHEXFILE_ML_TZ=%OUTPUTPATH%\%HW_VER%_%PROTOCOL_VER_ML_TZ%_v%SW_VER%_ML_TZ_SL%PACK_DATE%.hex
set OUTPUTBINFILE_ML_TZ=%OUTPUTPATH%\%HW_VER%_%PROTOCOL_VER_ML_TZ%_v%SW_VER%_ML_TZ_%PACK_DATE%.bin
set OUTPUTHEXFILE_SY=%OUTPUTPATH%\%HW_VER%_%PROTOCOL_VER_SY%_v%SW_VER%_SY_SL%PACK_DATE%.hex
set OUTPUTBINFILE_SY=%OUTPUTPATH%\%HW_VER%_%PROTOCOL_VER_SY%_v%SW_VER%_SY_%PACK_DATE%.bin
set ROMSTARTADDRESS=0x08000000
set APPADDRESS=0x08005800
set LOADERADDRESS=0x08000000
set SYSTEMSETTINGADDRESS=0x08004800
set SYSTEMSETTINGBACKUPADDRESS=0x08005000
set FLASHSIZE=0001B800

rem set SystemSettingPath=%cd%\..\SystemSetting.xml

rem 调用命令
hexFileMerge.exe %APPBIN% %LOADERBIN% %XMLFILE_ML_TZ% %OUTPUTHEXFILE_ML_TZ% %OUTPUTBINFILE_ML_TZ% %FLASHSIZE% %ROMSTARTADDRESS% %APPADDRESS% %LOADERADDRESS% %SYSTEMSETTINGADDRESS% %SYSTEMSETTINGBACKUPADDRESS% 
hexFileMerge.exe %APPBIN% %LOADERBIN% %XMLFILE_SY% %OUTPUTHEXFILE_SY% %OUTPUTBINFILE_SY% %FLASHSIZE% %ROMSTARTADDRESS% %APPADDRESS% %LOADERADDRESS% %SYSTEMSETTINGADDRESS% %SYSTEMSETTINGBACKUPADDRESS% 

del %OUTPUTHEXFILE_ML_TZ%
del %OUTPUTHEXFILE_SY%